[tool.robotpy-build.metadata]
name = "robotpy-halsim-ws"
description = "WPILib simulator websim Extensions"
author = "RobotPy Development Team"
author_email = "robotpy@googlegroups.com"
url = "https://github.com/robotpy/robotpy-halsim-gui"
license = "BSD-3-Clause"
install_requires = [
    "robotpy-hal~=2023.4.1",
    "robotpy-wpinet~=2023.4.1",
]

[tool.robotpy-build.metadata.entry_points]
robotpysimext = [
    "ws-server = halsim_ws.server",
    "ws-client = halsim_ws.client",
]


[build-system]
requires = [
    "robotpy-build<2024.0.0,>=2023.1.1",
    "robotpy-hal~=2023.4.1",
    "robotpy-wpinet~=2023.4.1",
]

[tool.robotpy-build]
base_package = "halsim_ws"

[tool.robotpy-build.wrappers."halsim_ws.server".maven_lib_download]
artifact_id = "halsim_ws_server"
group_id = "edu.wpi.first.halsim"
# repo_url = "https://frcmaven.wpi.edu/artifactory/release"
repo_url = "https://frcmaven.wpi.edu/artifactory/release"
version = "2023.4.1"

dlopenlibs = ["halsim_ws_server"]

[tool.robotpy-build.wrappers."halsim_ws.server"]
name = "server"
depends = ["wpiHal", "wpinet"]

[tool.robotpy-build.wrappers."halsim_ws.client".maven_lib_download]
artifact_id = "halsim_ws_client"
group_id = "edu.wpi.first.halsim"
# repo_url = "https://frcmaven.wpi.edu/artifactory/release"
repo_url = "https://frcmaven.wpi.edu/artifactory/release"
version = "2023.4.1"

dlopenlibs = ["halsim_ws_client"]

[tool.robotpy-build.wrappers."halsim_ws.client"]
name = "client"
depends = ["wpiHal", "wpinet", "wpiutil"]

