[build-system]
requires = [
    "robotpy-build>=2020.6.0,<2021.0.0",
    "robotpy-hal>=2021.2.2.0,<2022.0.0",
]

[tool.robotpy-build]
base_package = "halsim_ws"

[tool.robotpy-build.wrappers."halsim_ws.server".maven_lib_download]
artifact_id = "halsim_ws_server"
group_id = "edu.wpi.first.halsim"
repo_url = "https://frcmaven.wpi.edu/artifactory/release"
version = "2021.2.2"

dlopenlibs = ["halsim_ws_server"]

[tool.robotpy-build.wrappers."halsim_ws.server"]
name = "server"
depends = ["wpiHal"]

[tool.robotpy-build.wrappers."halsim_ws.client".maven_lib_download]
artifact_id = "halsim_ws_client"
group_id = "edu.wpi.first.halsim"
repo_url = "https://frcmaven.wpi.edu/artifactory/release"
version = "2021.3.1"

dlopenlibs = ["halsim_ws_client"]

[tool.robotpy-build.wrappers."halsim_ws.client"]
name = "client"
depends = ["wpiHal"]

[tool.robotpy-build.metadata]
name = "robotpy-halsim-ws"
description = "WPILib simulator websim Extensions"
author = "RobotPy Development Team"
author_email = "robotpy@googlegroups.com"
url = "https://github.com/robotpy/robotpy-halsim-gui"
license = "BSD-3-Clause"
install_requires = [
    "robotpy-hal>=2021.2.2.0,<2022.0.0",
]

[tool.robotpy-build.metadata.entry_points]
robotpysimext = [
    "ws-server = halsim_ws.server",
    "ws-client = halsim_ws.client",
]
